CREATE TABLE IF NOT EXISTS ADDRESSES
(
    ADDRESS_ID BIGSERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PROPERTIES
(
    PROPERTY_ID BIGSERIAL NOT NULL PRIMARY KEY,
    OWNER_ID VARCHAR(254) NOT NULL,
    PRICE_PER_NIGHT NUMERIC NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    DESCRIPTION TEXT,
    MAX_GUESTS INT,
    BEDROOMS INT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NOT NULL,

    CONSTRAINT FK_ADDRESS FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESERVATIONS
(
    RESERVATION_ID BIGSERIAL NOT NULL PRIMARY KEY,
    PROPERTY_ID BIGINT NOT NULL,
    GUEST_ID VARCHAR(254) NOT NULL,
    DATE_START DATE NOT NULL,
    DATE_END DATE NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    DATE_MODIFIED TIMESTAMP NOT NULL,

    CONSTRAINT FK_PROPERTIES FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTIES(PROPERTY_ID)
);



